import type { Metadata } from "next";
import { pressStart2P } from "@/components/Fonts/fonts";
import "./globals.css";
import Nav from "@/components/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pressStart2P.className} antialiased body `}>
        <Nav />
        <div className="w-10/12 xl:w-8/12 mx-auto">{children}</div>
      </body>
    </html>
  );
}
